### ISSUE TITLE
Can't copy and paste output

### ISSUE THREAD

**Issue by naartjie** [jasongilman/proto-repl#225]
This might be an issue with a plugin proto-repl is using, or my specific setup, but I am not able to select any of the output text (to copy and paste it for e.g.) in the proto-repl console.

Is anyone else experiencing this issue also? My whole Atom window just moves instead, when I hold mouse down and drag the cursor.

**Comment by carocad** [comment]
@naartjie the old versions of proto-repl didnt allow copying the results but the new ones should. Please check the CHANGELOG. 

On the other hand I already submited a PR to atom-ink to make it the default behavior. See https://github.com/JunoLab/atom-ink/pull/115

**Comment by jasongilman** [comment]
This was fixed in a past version.

**Comment by naartjie** [comment]
@jasongilman this is still happening here, maybe we're talking about slightly different things?

![proto](https://cloud.githubusercontent.com/assets/514563/24037871/40ff83d2-0b25-11e7-93a5-dd863da78e0e.gif)

I can click and drag to select the `(println "hello, proto-repl")` line of code, but if I click the output `hello, proto-repl` the editor moves. Is this an issue with Ink perhaps?

Versions:
Atom: `1.15.0`
proto-repl: `1.4.18`
ink: `0.6.5`
Mac OS X: `10.11.6`
